### PR TITLE
Handle chunked HTTP responses

### PR DESCRIPTION
**Pull request by grampajoe**
I started getting a lot of chunked responses from Last.fm (indicated by the "DEBUG: Chunked!" message), and decided to try adding support for them. There was already a branch for this, but it was a bit stale, so I hope you don't mind.

The responses from Last.fm haven't been very large, usually just "OK", so I'm not 100% confident in its correctness; but there haven't been problems in my testing so far. It might be wise to try it out for a while before considering merging.

### CODE REVIEW

**Comment by grampajoe** [comment]
@chx This gets rid of that error message; but you're right, not parsing the response doesn't actually affect anything.

**Comment by pioto** [comment]
This solves the DEBUG: Chunked for me, and stuff does seem to be scrobbled, despite the message to the contrary. But recently, I am also seeing this:

```
Invalid HTTP: HTTP/1.1 400 Bad Request
  from: http://post2.audioscrobbler.com:80/protocol_1.2
```

Did they deprecate the scrobbler protocol version that shell-fm is using, or something? http://www.audioscrobbler.net/ makes it seem like they may have?

More evidence that more code here may need a rewrite sooner or later:
- http://www.audioscrobbler.net/development/protocol/ (documentation for the protocol we seem to be using) says "use protocol 1.2.1 instead"
- http://www.last.fm/api/submissions says "This protocol [1.2.1] is now deprecated!"

**Comment by grampajoe** [comment]
@pioto Yes, shell-fm uses an old version of the Audioscrobbler protocol that's been deprecated for a while, but it looks like it still works. The 400 response is probably just a bug, and not a protocol thing. Maybe start a new issue and I or someone else can take a closer look at it?

Either way, upgrading to the new protocol would probably be a fun project.

**Comment by grampajoe** [comment]
This branch has been working perfectly for me. Is there anything else that needs to be done to get it pulled in?

**Comment by bartman** [comment]
Hmm, I am still getting 'Couldn't scrobble track' on this @grampajoe 's http_chunked branch.  Am I the only one?  Is there anything I should look at?

**Comment by ghost** [comment]
Sadly, this isn't the end of the story.  See the comment thread on commit cfd9a61.

(I agree that this is a better place to continue the discussion.)

**Comment by grampajoe** [comment]
Can anyone who isn't able to scrobble tracks do some more in-depth debugging? The client has been working fine for me, so I don't have an opportunity to see what the problem is.

**Comment by pioto** [comment]
I've tried attaching gdb to see what's happening, but then the issue magically goes away :p

But, it seems like `sscanf(status, "HTTP/%*f %u", & nstatus)` isn't returning 2... at least for me:

```
Invalid HTTP: HTTP/1.1 400 Bad Request
  from: http://post2.audioscrobbler.com:80/protocol_1.2
```

my reading of sscanf(2)'s manpage, though, indicates that I should just be returning 1 here, in a normal looking case, since there's only 1 capture.

```
An  optional  '*' assignment-suppression character: scanf() reads input as directed
by the conversion specification, but discards the input.  No corresponding  pointer
argument  is  required, and this specification is not included in the count of suc‐
cessful assignments returned by scanf().
```

So, I'd expect that I should really be seeing:

```
HTTP Response: HTTP/1.1 400 Bad Request
```

Of course, that doesn't really change the fact that the server is giving me a 400 error for some reason. Until I can get gdb to break somewhere around there for me, though, I won't be able to figure out much more. Or, until I add a bunch of DEBUG statements...

**Comment by bartman** [comment]
@grampajoe , strangely enough after I rebuilt in DEBUG mode, it works.  Will play some more with it.

**Comment by bartman** [comment]
I merged in after a ~day of testing.  While I had some issues this morning, I hadn't seen a 'Couldn't scrobble track' error since then.  Even if it's not fully working for everyone, it's at least no worse than what we had before, and it seems to work for some people perfectly.

@grampajoe , thank you for your contribution.

**Comment by grampajoe** [comment]
Thanks! I'll keep looking into why some people are having scrobbling problems.

**Comment by pioto** [comment]
Well, now I upgraded my workstation, and I think I'm more or less now on a vanilla 'jkramer/master' branch again, along with some local changes (for work on a .dpkg) -- but otherwise I'm the same as 679a0e238d78864c4340cedc3615aa234ef3e440

Now, though, I get `Couldn't scrobble track(s).` instead of the weird error I got before.

But, I see you just merged this to master, so I'll do the same and see how things go...

**Comment by ghost** [comment]
On Fri, Apr 20, 2012 at 9:39 AM, Mike Kelly
reply@reply.github.com
wrote:

Mike> Well, now I upgraded my workstation, and I think I'm more or less
Mike> now on a vanilla 'jkramer/master' branch again, along with some
Mike> local changes (for work on a .dpkg) -- but otherwise I'm the same
Mike> as 679a0e238d78864c4340cedc3615aa234ef3e440

Mike> Now, though, I get `Couldn't scrobble track(s).` instead of the
Mike> weird error I got before.

Mike> But, I see you just merged this to master, so I'll do the same and
Mike> see how things go...

Be sure to check if your last.fm profile is actually updated after you
exit the shell-fm player, and perhaps after you use another player and
scrobbler.  It seems to be easy to believe that everything works once
you see the "now playing" info on the site but alas as I learned it is
not so.

## 

Ian Zimmerman
gpg public key: 1024D/C6FF61AD
fingerprint: 66DC D68F 5C1B 4D71 2EE5 BD03 8A00 786C C6FF 61AD
http://www.gravatar.com/avatar/c66875cda51109f76c6312f4d4743d1e.png
Rule 420: All persons more than eight miles high to leave the court.

**Comment by bartman** [comment]
I've been running with changes 3c48c8aebe91bdafd1eda2de1cc61ada706b245b (after merging them in on 3ab4e23c5536d40a5e262e5cbdea23d8f1b71efc) for over a day now.  No error messages here, and getting updates on last.fm profile.

Thanks again @grampajoe

**Comment by pioto** [comment]
Yep, after re-merging master, I get no errors scrobbling at all. _shrug_

**Comment by pioto** [comment]
And, confirmed that things are actually showing up as scrobbled on last.fm's site. So, "fixed" for me, somehow.

**Comment by jkramer** [comment]
Sorry for not helping out here, I just didn't get any of the problems described here for a long time. Scrobbling still works fine here, but I got the chunked message a few times and finished the implementation I had started long time ago in the chunked branch. The current version is in the "openssl" branch (yeah, it got mixed up a little :)), I'd be happy if you could try it. Also thanks to @grampajoe for his fix, I'm not sure it's future-proof though. :) It reads the full response at a time, so if last.fm decides to use chunked content for the stream as well things will get complicated. I think my approach will handle this, but see for yourself and let me know what you think.

Regards,
Jonas

**Comment by grampajoe** [comment]
Yeah, you're right, I didn't even consider that the audio stream could be chunked as well. I'll try out the openssl branch. Thanks!

**Pull request merged**
